flaskapp/webapp/admin/__init__.py
from flask_admin import Admin
from flask_admin.consts import ICON_TYPE_FONT_AWESOME
from webapp import db
# from .routes import CustomView, CustomModelView, CustomFileAdmin
from ..auth.models import User, Role
from ..mainapp.models import Features, Feedback,  Countries, SearcHDestination
from ..users.models import Search

import csv 
admin = Admin()


def create_module(app, **kwargs):
    #admin.init_app(app)
    #admin.add_view(CustomView(name='Custom'))
    #user_model = User
    #models = [user_model, Role, Features, Feedback, SearcHDestination, Search, Countries]
    #for model in models:
    #    admin.add_view(CustomModelView(model, db.session, category='Database Models'))

    #admin.add_view(CustomFileAdmin(app.static_folder,'/static/', name='Static Files'))

    from .routes import admin_blueprint
    app.register_blueprint(admin_blueprint)


flaskapp/webapp/admin/routes.py
import os 
import pickle
import random
import datetime
from datetime import datetime, timedelta
import base64
import io

from flask import (Blueprint,render_template, redirect, url_for, 
                   flash, session, request, jsonify, current_app, abort)
from flask_login import login_required, current_user
from sqlalchemy import exc

import pandas as pd
import matplotlib.pyplot as plt

from webapp import db
from ..auth import has_role, permission_required, admin_required
from ..auth.models import User, Role
from ..mainapp.models import Features, Feedback
from .models import Admin
from .forms import editAdmin, editProfile
from ..reports.utils import get_model_score 


admin_blueprint = Blueprint('admin', __name__,
                            static_folder='../static/admin',
                            template_folder='../templates/admin',
                            url_prefix="/letsgo/admin"
                            )

dire = os.path.dirname(__file__)
model = pickle.load(open(os.path.join(dire, "pickle_objects", "Cat_v3.pkl"), 'rb'))
senti_clf = pickle.load(open(os.path.join(dire, "pickle_objects", "classifier.pkl"), 'rb'))
importance = pd.read_csv("/home/riri/Desktop/expenditure/src/models/notebooks/classification/Importances.csv")
imps = importance.to_dict(orient='records')
importance.plot(kind='barh')
plt.xlabel('Importance')
plt.ylabel('Features')
plt.title('Feature Importance')

img = io.BytesIO()
plt.savefig(img, format='png')
img.seek(0)

plot_url = base64.b64encode(img.getvalue()).decode()

def fetch_data():
    results = Features.query.all()
    return [{column.name: getattr(row, column.name) for column in row.__table__.columns} for row in results]

@admin_blueprint.route("/features", methods=['GET', 'POST'])
@login_required
@admin_required
def fetch_features():
    result = fetch_data()
    return jsonify(result)

@admin_blueprint.route("/")
@login_required
@admin_required
def admindashboard():
    date_from = datetime.now() - timedelta(days=90)
    all_u = User.query.all()
    new = User.query.filter(User.date_created > date_from).all()
    users = random.sample(all_u, min(3, len(all_u)))
    feedback = Feedback.query.all()
    feedback = random.sample(feedback, min(5, len(feedback))) 
    features = Features.query.order_by(Features.date.desc()).all()
    feats = random.sample(features, min(5, len(features)))
    late_feed = Feedback.query.order_by(Feedback.date.desc()).limit(10).all()
    return render_template('dashboard.html', users=users, all=all_u, 
                           score=get_model_score(), new=new, model=model, 
                           feedback=feedback, features=feats, all_f=features,
                           feed=late_feed, imps=imps, plot=plot_url)
    
@admin_blueprint.route("/users", methods=['GET', 'POST'])
@login_required
@admin_required
def users():
    features = Features.query.all()
    page = request.args.get('page', 1, type=int)
    users = User.query.order_by(User.last_seen.desc())
    pagination = db.paginate(users, page=page, per_page=7, error_out=False)
    users = pagination.items
    return render_template("admin/users.html", users=users, 
                           pagination=pagination, features=features)

@admin_blueprint.route("/feedback")
@login_required
@admin_required
def feed():
    users = User.query.all()
    feat = Features.query.all()
    page = request.args.get('page', 1, type=int)
    feed = Feedback.query.order_by(Feedback.date.desc())
    pagination = db.paginate(feed, page=page, per_page=10, error_out=False)
    feedback = pagination.items
    return render_template("admin/feedback.html", feedback=feedback, pagination=pagination, 
                           features=feat, users=users, zip=zip, enumerate=enumerate)
@admin_blueprint.route("/all_features")
@login_required
@admin_required
def features():
    users = User.query.all()
    feats = Features.query.order_by(Features.date.asc()).order_by(Features.id.asc())
    page = request.args.get('page', 1, type=int)
    pagination = db.paginate(feats, page=page, per_page=10, error_out=False)
    feats = pagination.items

    return render_template("admin/features.html", features=feats, 
                           pagination=pagination, users=users)

@admin_blueprint.route("/<string:username>/admin-profile/")
@login_required
@admin_required
def profile(username):
    user = Admin.query.filter_by(username=username).first() or User.query.filter_by(username=username).first()
    if not user:
        flash("User not found or user is not an administrator", category="warning") 
    return render_template("admin/profile.html", user=user)


@admin_blueprint.route("/<string:username>/admin-profile/update", methods=['POST', 'GET'])
@login_required
@admin_required
def edit_admin(username):
    user = Admin.query.filter_by(username=username).first_or_404() 
    if not user:
        user = User.query.filter_by(username=username).first()
    if not user.is_administrator():
        return redirect(url_for('.user_profile', username=user.username))
    form = editAdmin()
    if form.validate_on_submit():
        admin = Admin()

        admin.name = form.name.data
        admin.email = form.email.data
        admin.username = user.username
        admin.mobile = form.mobile.data
        admin.agency = form.agency.data
        admin.agency_email = form.agency_email.data
        admin.agency_mobile = form.agency_mobile.data
        admin.agency_address = form.agency_address.data
        try:
            db.session.add(admin)
            db.session.commit()
            flash("Administrator profile details updated succesfully", category="info")
            return redirect(url_for('.user_profile', username=user.username))
        except BaseException as e:
            db.session.rollback()
            flash("Administrator profile not updated!: {}".format(e), category="warning")
            return redirect(url_for('.profile', username=current_user.username))
    
    form.name.data = user.name
    form.email.data = user.email
    form.agency.data = user.agency
    form.mobile.data = user.mobile
    form.agency_email.data = user.agency_email
    form.agency_address.data = user.agency_address
    form.agency_mobile.data = user.agency_mobile
    
    return render_template("admin/editadmin.html", form=form, user=user)

@admin_blueprint.route('/<string:username>@user-profile', methods=['GET', 'POST'])
@login_required
@admin_required
def user_profile(username):
    user = User.query.filter_by(username=username).first()
    if not user:
        flash('No such user with the given username', 'warning')
        return redirect(url_for('.users')) 
    
    return render_template('/user/view.html', user=user)

@admin_blueprint.route('/@<string:username>/user-profile/update', methods=['GET', 'POST'])
@login_required
@admin_required
def update_profile(username):
    user = Admin.query.filter_by(username=username).first() or User.query.filter_by(username=username).first()
    if not user:
        flash("User with that such username doesn't exist!.", "warning")
        return redirect(url_for('.users'))
    form = editProfile(user=user)
    if request.method == 'POST' and form.validate_on_submit():
        user.email = form.email.data
        user.full_name = form.name.data
        user.username = form.username.data
        user.mobile = form.mobile.data
        user.role = Role.query.get(form.role.data)
        user.location = form.location.data
        user.about = form.about.data
        user.confirmed = form.confirmed.data
        try:
            db.session.add(user)
            db.session.commit()
            flash('User details updated successfully.', category="info")
            return redirect(url_for('.user_profile', username=user.username))
        except Exception:
            db.session.rollback()
            flash("User details not updated.", 'info')
    
    form.email.data = user.email
    form.name.data = user.full_name
    form.username.data = user.username
    form.role.data = user.role
    form.location.data = user.location
    form.about.data = user.about
    form.confirmed.data = user.confirmed
    
    return render_template('/user/editProfile.html', form=form, user=user)

@admin_blueprint.route('/remover_user/<username>/', methods=['GET', 'POST'])
@login_required
@admin_required
def delete_profile(username):
    user = User.query.filter_by(username=username).first()
    if user:
        try: 
            db.session.delete(user)
            db.session.commit()
            flash(f"User {user.username} removed successfully", category="info")
            return redirect(url_for('.users'))
        except Exception:
            db.session.rollback()
            flash("User couldn't be removed.", 'info')
            return redirect(url_for('.users'))
    else:
        flash("User with such username not found", category='warning')
        return redirect(url_for('.users'))

flaskapp/webapp/api_1_0/__init__.py
from flask_restful import Api
from .feedback.controllers import FeedbackApi

rest = Api()

def create_module(app, **kwargs):
       rest.add_resource(
            FeedbackApi,
            '/api/feed',
            '/api/feed/<int:feed_id>')
       rest.init_app(app)

flaskapp/webapp/babel/__init__.py
from flask import has_request_context, session, request, current_app
from flask_babel import Babel


def get_locale():
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])

babel = Babel(locale_selector=get_locale)

def create_module(app, **kwargs):
    babel.init_app(app)
    from .routes import babel_blueprint
    app.register_blueprint(babel_blueprint)



flaskapp/webapp/mainapp/routes.py
import logging

import json
import random

import numpy as np

from sqlalchemy import exc

from flask import render_template, url_for, redirect, Blueprint, flash, request, session, jsonify
from flask_login import login_required, current_user

from webapp import db, cache
from webapp.auth.models import User
from .models import Countries, Features, Feedback, SearcHDestination
from .forms import FeaturesForm, feedbackform, search

from ..users.forms import feedback
from ..predict import predict_category, predict_cost, predict_feed_sentiment, staycation
from ..train import train_clf


app_blueprint = Blueprint('app', __name__,
                          static_folder="../static", template_folder="../templates/app", 
                          url_prefix="/letsgo")

@app_blueprint.route("/", methods=['GET', 'POST'])
@cache.cached(timeout=1)
def index():
    users = User.query.all()
    feedback = Feedback.query.all()
    feedback = random.sample(feedback, min(3, len(feedback)))
    
    form = search()
    if request.method == 'POST' and form.validate_on_submit():
        query = form.search.data
        if query:
            session['destination'] = query
            search_query = SearcHDestination(dest=form.search.data)
            db.session.add(search_query)
            db.session.commit()
            return redirect(url_for('app.searchdestination', destination=session.get("destination")))
        flash("Kindly tell us your search destination.")
    return render_template('index.html', users=users,
                            feedback=feedback, form=form, 
                            dest=session.get("destination"), zip=zip)

@app_blueprint.route("/destinations/<destination>")
def searchdestination(destination):
    dest = session.get("destination")
    return render_template("destinations.html", dest=session.get('destination'))

@app_blueprint.route('/form', methods=['GET', 'POST'])
@cache.cached(timeout=2)
def form():    
    form = FeaturesForm(request.form)
    if request.method == 'POST' and form.validate():
        country = form.country.data
        bururi = Countries.query.filter_by(Country=country).first() #Features.bururi.Region
        region = bururi.Region
        sub_region = bururi.Sub_Region
        age = form.age.data
        companion = form.companion.data
        purpose = form.purpose.data
        activity = form.activity.data
        info = form.info.data
        arrangement = form.arrangement.data
        pack_tra_int = form.pack_tra_int.data
        pack_acc = form.pack_acc.data
        main_nights = int(form.main_nights.data)
        zanzi_nights = int(form.zanzi_nights.data)
        duration = main_nights + zanzi_nights
        stay = staycation(duration)
        try:
            submitted = [country, age, companion, purpose, activity, info, arrangement, pack_tra_int,
                     pack_acc, region, sub_region, duration, stay]
            category, probability = predict_category(submitted)
            regress = [country, age, companion, purpose, activity, info, arrangement, pack_tra_int,
                     pack_acc, main_nights, region, sub_region, duration]
            cost = predict_cost(regress)
            if current_user.is_authenticated:
                user_id = current_user.id
            else:
                user_id = None
            features = Features(country=country, region=region, sub_region=sub_region, age_group=age, travel_with=companion, 
                     purpose=purpose, main_activity=activity, info_source=info, tour_arrangement=arrangement, 
                     package_transport_int=pack_tra_int, package_accomodation=pack_acc,
                     night_mainland=main_nights, night_zanzibar=zanzi_nights, duration=duration,
                     staycation=stay, predicted_category=category, probability=probability, total_cost=cost,
                     user_id=user_id)
            db.session.add(features)
            db.session.flush()
            session['feature_id'] = features.id
            session['user'] = features.user_id
            db.session.commit()
            return redirect(url_for('.predict'))
        except exc.IntegrityError as e:
            db.session.rollback() 
            flash("An error occured while generating your predictions", 'warning')
            raise e
    return render_template('app/form.html', form=form)

@app_blueprint.route('/prediction', methods=['POST', 'GET'])
def predict():
    feature_id = session.get('feature_id')
    feature = Features.query.filter_by(id=feature_id).first_or_404()
    if not feature_id or current_user.is_authenticated and ( current_user.id != session.get('user')):
        flash("Kindly provide your travel details first", category="info")
        return redirect(url_for('.form'))
    form = feedback()
    if request.method == 'POST' and form.validate_on_submit():
        feed = form.feed.data
        sentiment, proba = predict_feed_sentiment(feed)
        user_id = current_user.id
        try:
            user_feedback = Feedback(feed=feed, sentiment=sentiment, probability=proba, 
                                 feature_id=feature_id,user_id= user_id)
            db.session.add(user_feedback)
            db.session.commit()
            flash("Thank you for your feedback.", category="info")
            return redirect(url_for('.predict'))
        except exc.IntegrityError as e:
            flash("Your feedback was not sent, our apologies.", category="info")
            logging.error("Error while adding user feedback: {}".format(e))
    return render_template('app/result.html', feature=feature, form=form)

@app_blueprint.route('/thanks', methods=['GET', 'POST'])
@login_required
def thanks():
    if request.method == 'POST':
        feed = request.form['feedback_button']
        if feed == 'Disatisfied':
                return redirect(url_for('app.sema'))
        flash("Thank you, we're very happy to hear that. 🤗🎆🎇", category='info')
    return render_template('app/thanks.html')

@app_blueprint.route('/feedback', methods=['GET', 'POST'])
@login_required
def sema():
    form = feedbackform(request.form)
    if request.method == 'POST':
        feed = form.feed.data
        senti, proba = predict_feed_sentiment(feed)
        details = Features.query.order_by(Features.id.desc()).first()
        id = details.id
        uhoro = Feedback(feed=feed, sentiment=senti, probability=proba, feature_id=id, user_id=current_user.id)

        db.session.add(uhoro)
        db.session.commit() 

        flash('Feedback received, thank you for your time.')
        return redirect(url_for('suser.activity', username=current_user.username))
 
    return render_template('app/feedback.html', form=form)

flaskapp/webapp/reports/__init__.py
def create_module(app, **kwargs):
    from .routes import reports_blueprint
    
    app.register_blueprint(reports_blueprint)

flaskapp/webapp/templates/users/api.html
{% extends 'Base.html' %}

{% block title %} LetsGo | Api_Data {% endblock %}

{% block content %}
<section>
    <h1>Properties</h1>
    <ul>
        {% for property in properties %}
            <li>{{ property }} - {{ property.__typename }}</li>
        {% endfor %}      
    </ul>
    <h1>Availabity Status:</h1>
    <ul>
        {% for avail in availability %}
        <li>{{ avail }} - {{ avail.__typename }}</li>
        {% endfor %}
    </ul>

    <h1>Rooms Left: </h1>
    <ul>
        {% for room in roomsleft %}
        <li>{{ room }} - {{ room.__typename }}</li>
        {% endfor %}
    </ul>
    {{ data }}
</section>
{% endblock %}

flaskapp/webapp/templates/users/editProfile.html
{% extends 'base.html' %}
{% import 'macros/auth.html' as macro %}

{% block title %}LetsGo | {{ (user.username).split()[0] }} Profile{% endblock %}

{% block content %}
{% include 'include/navigation.html' %}
<section class="edit-profile">
    <div class="profile-items">
        <div class="item1">
            <h1>Edit your profile.</h1>
            <img src="{{ current_user.gravatar(100) }}" alt="{{ current_user.username }}" title="{{ current_user.username }} avatar.">
            <form action="{{ url_for('suser.update', username=current_user.username) }}" method="POST">
                {{ form.hidden_tag() }}
                {% for field in form %}
                {% if field.widget.input_type != 'hidden' %}
                    {% if field.type != 'TextAreaField' %}
                    <div class="block">
                        {{ field.label }}
                        {{ field(class_='field', placeholder=field.label.text) }} 
                        {% for e in field.errors %}
                            <span class="help-block">{{ e }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    <div class="block">
                        {{ field.label }}
                        {{ field(class_='field', id_='text-area', placeholder=field.label.text) }}
                            {% for e in field.errors %}
                        <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    </div>
                    {% endif %}
                {% endif %}
                {% endfor %}
                <div class="buttons">
                    <a class="btn btn-secondary" onclick="goBack()">Back</a>
                    <button class="btn btn-success" type="submit">Update Profile</button>
                </div>
            </form>       
        </div>
        <div class="item2">

        </div>
    </div>
</section>
<script>
    function goBack(){
        window.history.back()
    }
</script>

{% endblock %}

flaskapp/webapp/templates/users/myprofile.html
{% extends 'base.html' %}

{% block title %}
    LetsGo |
    {% if user.id == current_user.id %}
        Hey {{ (user.username).split()[0] }} :)
    {% elif current_user.is_authenticated and current_user.is_administrator() %}
        {{ (user.username).split()[0] }} Profile 
    {% endif %}
{% endblock %}

{% block content %}
{% include 'include/navigation.html' %}
<section class="profile">
    <div class="header" id="header">
        {% if current_user != user and current_user.is_administrator() %}
            <p style="color: brown;"><i class="fa fa-info-circle"></i> 
                Viewing {% if not ((user.username).split()[0]).endswith('s') %} 
                    {{ (user.username).split()[0] }}'s {% else %} {{ (user.username).split()[0] }} {% endif %} 
                profile as administrator.
            </p>
            <p class="honcho" data-url="{{ url_for('admin.users') }}" id="user-tab">Back to users</p>
        {% else %}
            <h3 id="jambo">Jambo 
                {% if user.full_name %}
                    {{ (user.full_name).split()[0] }}, 
                {% else %}
                    {{ user.username | title }}
                {% endif %}
                glad to see you here.
            </h3>
            <button type="button" id="exit">
                <span aria-hidden="true">&times;</span>
            </button>
            {% if user.is_administrator() %}
                <p class="honcho" data-url="{{ url_for('admin.profile', username=user.username) }}" id="user-tab">Admin View</p>
            {% endif %}
        {% endif %} 
    </div> 
    <div class="profile-items">
        <div class="over">
            {% if user.gravatar %}
                <img src="{{ user.gravatar(256) }}" alt="">
            {% else %}
                <img src="{{ url_for('static', filename='/images/admin.png') }}" alt="">
            {% endif %}
            {% if user.location %}
                <a href="https://www.google.maps?q={{user.location}}">
                    <i class="fa fa-map-marker"></i>
                    {{user.location}}
                </a>
            {% endif %}
            {% if user.full_name %}
                <span><i class="fa fa-user-tag"></i>{{ user.full_name | title }}</span>
            {% endif %}
            <p><i class="fa fa-at"></i> {{ user.username }}</p>
            {% if current_user.is_administrator() %}
                <p><i class="fa fa-clock"></i> Last activity was {{ moment(user.last_seen).fromNow() }}</p>
            {% endif %}
        </div>
        <div class="profile-cards">
            <div class="profile-card">
                <span class="fa-stack fa-3x">
                     <i class="fa fa-square fa-stack"></i><i class="fa fa-user-circle fa-stack-1x fa-inverse"></i>
                </span>
                <h2>Profile</h2>
                <p class="links cl-effect-1">
                    {% if current_user != user and current_user.is_administrator() %}
                        <a href="#" data-bs-toggle="modal" data-bs-target="#ProfileBackdrop">Manage {{ (user.username).split()[0] }} Profile</a>
                    {% else %}
                        <a href="#" data-bs-toggle="modal" data-bs-target="#ProfileBackdrop">Manage Your Profile</a>
                    {% endif %}
                    <div class="modal fade" id="ProfileBackdrop" data-bs-keyboard="false" tabindex="-1" aria-labelledby="PofileBackdropLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="ProfileBackdropLabel">
                                        {% if current_user != user and current_user.is_administrator() %}
                                            <span style="font-weight: 600;">{{ (user.username).split()[0] | title }}</span> Profile
                                        {% else %}
                                            Hey <span style="font-weight: 600;">{{ (user.username).split()[0] | title }} </span>:)
                                        {% endif %}                                        
                                        <span class="text-uppercase" >
                                    </h5>
                                </div>
                                <div class="modal-body text-start">
                                    {% if user.username or user.location %}
                                        {% if user.username %}
                                            {% if user.full_name %}
                                            <p><i class="fa fa-user-circle"></i> Name: <span>{{ user.full_name }}</span></p>
                                            {% endif %}
                                            {% if user.email %}
                                                {% if current_user.is_administrator() %}
                                                    <p><i class="fa fa-envelope"></i> Email: <a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
                                                {% else %}
                                                    <p><i class="fa fa-envelope"></i> Email: <span>{{ user.email }}</span> </p>
                                                {% endif %}
                                            {% endif %}                                            
                                           <p><i class="fa fa-user-tag"></i> Username: <span>{{ user.username }}</span> </p>
                                        {% endif %}
                                    <div>
                                        {% if user.location %}
                                        <p><i class="fa fa-map-marker"></i> From: 
                                            <span> 
                                                <a href="https://maps.google.com/?q={{ user.location }}"target="_blank">{{ user.location }}</a>
                                            </span>
                                        </p>
                                        {% endif %}
                                    </div>
                                    {% endif %}
                                    {% if user.about %}
                                    <div>
                                        <p><i class="fa fa-medal"></i> About me: <span> {{ user.about }}</span></p>
                                    </div>
                                    {% endif %}
                                    <p><i class="fa fa-calendar"></i> Member Since: <span>{{ moment(user.date_created).format('LL') }}</span>.</p>
                                    {% if current_user.is_administrator() %}
                                        <p> <i class="fa fa-clock"></i> Last Seen: <span>{{ moment(user.last_seen).fromNow() }}</span></p>
                                    {% endif %}
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary"
                                        data-bs-dismiss="modal">Close</button>
                                    {% if current_user != user and current_user.is_administrator() %}
                                        <a type="button"  href="{{ url_for('admin.user_profile', username=user.username) }}" class="btn btn-primary">
                                            Edit Profile
                                        </a>                                        
                                    {% else %}
                                        <a type="button"  href="{{ url_for('suser.update', username=current_user.username) }}" class="btn btn-primary">
                                            Edit Profile
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </p>
            </div>
            <div class="profile-card">
                <span class="fa-stack fa-3x">
                    <i class="fa fa-square fa-stack "></i><i class="fa fa-face-grin-stars fa-stack-1x fa-inverse"></i>
                </span>
                {% if current_user != user and current_user.is_administrator() %}
                    <h2>Activity</h2>
                    <p class="links cl-effect-1">
                        <a href="{{ url_for('suser.activity', username=user.username) }}">
                            See {{ (user.username).split()[0] }}'s Activity
                        </a>
                    </p>
                {% else %}
                    <h2>My Activity</h2>
                    <p class="links cl-effect-1">
                        <a href="{{ url_for('suser.activity', username=user.username) }}">
                            See Your Activity
                        </a>
                    </p>
                {% endif %}
            </div>    
        </div>
    </div>
    <div class="prof-footer">
        <p>&copy;2024. LetsGo. All rights reseved.</p>
        <p>Made with <i class="fa fa-fire"></i> and<i class="fa fa-heart"></i>by LetsGo Team.</p>
    </div>
</section>
{% endblock %}
{% block js %}
    {{ super() }}
    {{ moment.include_moment() }}
    <script>
        var users = document.getElementById("user-tab");
        var jambo = document.getElementById("header");
        var mia = document.getElementById("exit");

        users.addEventListener('click', function(){
            url = users.getAttribute('data-url');

            setTimeout(function(){
                window.location.href = url;
            }, 1000);

            this.style.cursor = 'progress';
        });

        mia.addEventListener('click', function(){
            jambo.classList.add('hide');
        });
    </script>
{% endblock %}