flaskapp/webapp/admin/models.py
from flask_admin.contrib.sqla import ModelView


from webapp import db

class CustomModelView(ModelView):
    pass
    
class Admin(db.Model):
    __tablename__ = "superusers"

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100))
    email = db.Column(db.String(100), unique=True, index=True)
    username =  db.Column(db.String(50), unique=True)
    mobile = db.Column(db.String(20), unique=True)
    agency = db.Column(db.String(255))
    agency_email = db.Column(db.String(100))
    agency_mobile = db.Column(db.String(20))
    agency_address = db.Column(db.String(255))
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id'))
    role_id = db.Column(db.Integer(), db.ForeignKey('roles.id'))
    roles = db.relationship('Role', backref='admin')
    users = db.relationship('User', backref='admin')

    def is_administrator(self):
        return True

flaskapp/webapp/__init__.py
from flask import Flask, render_template, request, jsonify
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from config import DevConfig, TestConfig
from flask_moment import Moment
from flask_debugtoolbar import DebugToolbarExtension
from flask_caching import Cache

db = SQLAlchemy()
migrate = Migrate()
moment = Moment()
debug_tool = DebugToolbarExtension()
cache = Cache()

def page_not_found(e):
    if request.accept_mimetypes.accept_json and \
    not request.accept_mimetypes.accept_html:
        response = jsonify({'error': 'not found'})
        response.status_code = 404
        return response
    return render_template('errors/404.html'), 404

def internal_server_error(e):
    if request.accept_mimetypes.accept_json and \
    not request.accept_mimetypes.accept_html:
        response = jsonify({'error': 'internal server error'})
        response.status_code = 500
        return response
    return render_template('errors/500.html'), 500

def forbidden(e):
    if request.accept_mimetypes.accept_json and \
    not request.accept_mimetypes.accept_html:
        response = jsonify({'error': 'forbidden', 'message':e})
        response.status_code = 403
        return response
    return render_template('errors/403.html'), 403

def not_allowed(e):
    if request.accept_mimetypes.accept_json and \
    not request.accept_mimetypes.accept_html:
        response = jsonify({"error":"not allowed", "message": e })
        response.status_code = 405
        return response
    return render_template('errors/405.html'), 405

def create_app(object_name):
    app = Flask(__name__)
    app.config.from_object(TestConfig)

    @app.after_request
    def add_header(response):
        response.cache_control.no_store = True
        return response
    
    db.init_app(app)
    migrate.init_app(app, db)
    moment.init_app(app)
    # debug_tool.init_app(app)
    cache.init_app(app)

    from .mainapp import create_module as app_create_module
    from .admin import create_module as admin_create_module
    from .reports import create_module as report_create_module
    from .babel import create_module as babel_create_module
    from .auth import create_module as auth_create_module
    from .users import create_module as user_create_module
    from .api_1_0 import create_module as api_create_module
    from .dashapp import init_dash
    
    app_create_module(app)
    auth_create_module(app)
    admin_create_module(app)
    report_create_module(app)
    babel_create_module(app)
    user_create_module(app)
    api_create_module(app)

    app.register_error_handler(404, page_not_found) 
    app.register_error_handler(500, internal_server_error)
    app.register_error_handler(403, forbidden)
    app.register_error_handler(405, not_allowed)

    # app = init_dash(app)
    return app

flaskapp/webapp/admin/__init__.py
from flask_admin import Admin
from flask_admin.consts import ICON_TYPE_FONT_AWESOME
from webapp import db
# from .routes import CustomView, CustomModelView, CustomFileAdmin
from ..auth.models import User, Role
from ..mainapp.models import Features, Feedback,  Countries, SearcHDestination
from ..users.models import Search

import csv 
admin = Admin()


def create_module(app, **kwargs):
    #admin.init_app(app)
    #admin.add_view(CustomView(name='Custom'))
    #user_model = User
    #models = [user_model, Role, Features, Feedback, SearcHDestination, Search, Countries]
    #for model in models:
    #    admin.add_view(CustomModelView(model, db.session, category='Database Models'))

    #admin.add_view(CustomFileAdmin(app.static_folder,'/static/', name='Static Files'))

    from .routes import admin_blueprint
    app.register_blueprint(admin_blueprint)


flaskapp/webapp/api_1_0/__init__.py
from flask_restful import Api
from .feedback.controllers import FeedbackApi

rest = Api()

def create_module(app, **kwargs):
       rest.add_resource(
            FeedbackApi,
            '/api/feed',
            '/api/feed/<int:feed_id>')
       rest.init_app(app)

flaskapp/webapp/api_1_0/feedback/controllers.py
import datetime

from flask import abort
from flask_restful import Resource, fields, marshal_with
from flask_jwt_extended import jwt_required, get_jwt_identity

from ...mainapp.models import Feedback
from ...auth.models import User

from .fields import HTMLField
from .parsers import feed_req_parser

feed = {
    'id': fields.Integer(),
    # 'author': fields.String(attribute=lambda x: x.feature_id),
    'feedback': fields.String(),
    'sentiment': HTMLField(),
    'probability': fields.String(),
    'feedback_date': fields.DateTime(dt_format='iso8601')
}

class FeedbackApi(Resource):
    @marshal_with(feed)
    @jwt_required
    def get(self, feed_id=None):
        if feed_id:
            feedback = Feedback.query.get(feed_id)
            if not feedback:
                abort(404)
            return feedback
        else:
            feedbacks = Feedback.query.all()
            return feedbacks
        


flaskapp/webapp/babel/__init__.py
from flask import has_request_context, session, request, current_app
from flask_babel import Babel


def get_locale():
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])

babel = Babel(locale_selector=get_locale)

def create_module(app, **kwargs):
    babel.init_app(app)
    from .routes import babel_blueprint
    app.register_blueprint(babel_blueprint)



flaskapp/webapp/babel/routes.py
from flask import Blueprint, redirect, url_for, session

babel_blueprint = Blueprint('babel', __name__, url_prefix="/letsgo")

@babel_blueprint.route('/<string:locale>')
def index(locale):
    session[locale] = locale
    return redirect(url_for('app.index'))

flaskapp/webapp/dashapp/__init__.py
from dash import Dash
import os 

def init_dash(server):

    external_stylesheets = [
        {
            "href": (
                "assets/css/style.css"
                ),
            "rel": "stylesheet"
         }
    ]
    external_scripts = []
    meta_viewport = [
        {
            "name": "viewport",
            "content": "width=device-width, initial-scale=1, shrink-to-fit=no",
        }
    ]

    #curr_dir = os.getcwd() + '/webapp/dashapp/assets'
    dire = os.path.dirname(__file__)
    ass_path = os.path.join(dire, 'assets')

    app = Dash(
        server=server, 
        routes_pathname_prefix='/letsgo/admin/dashboard/',
        assets_folder= ass_path,
        external_stylesheets=external_stylesheets,
        external_scripts=external_scripts,
        meta_tags=meta_viewport)
    
    app.title = "LetsGo | Dashboard"
    app._favicon = 'logo.ico'

    from .layouts import dash_layout
    from .callbacks import dash_callbacks

    with server.app_context():
        
        app.layout = dash_layout(app)

        dash_callbacks(app)

    return app.server

flaskapp/webapp/mainapp/__init__.py
import csv

from .models import Countries
from webapp import db

def create_module(app, **kwargs):
    """Creates and registers the main application blueprint. 

    Args:
        app: An instance of flask app.
    """
    from .routes import app_blueprint
    app.register_blueprint(app_blueprint)
    
    # with app.app_context():
    #     if not Countries.query.all():
    #         with open("/home/riri/Desktop/expenditure/Datasets/all.csv", 'r') as csvfile:
    #             reader = csv.DictReader(csvfile)
    #             for row in reader:
    #                 country = Countries(Country=row["name"], Alpha_Code=row["alpha-3"], 
    #                                     Region=row["region"],Sub_Region=row["sub-region"]) 
                    
    #                 db.session.add(country)
    #                 db.session.commit()  

flaskapp/webapp/mainapp/routes.py
import logging

import json
import random

import numpy as np

from sqlalchemy import exc

from flask import render_template, url_for, redirect, Blueprint, flash, request, session, jsonify
from flask_login import login_required, current_user

from webapp import db, cache
from webapp.auth.models import User
from .models import Countries, Features, Feedback, SearcHDestination
from .forms import FeaturesForm, feedbackform, search

from ..users.forms import feedback
from ..predict import predict_category, predict_cost, predict_feed_sentiment, staycation
from ..train import train_clf


app_blueprint = Blueprint('app', __name__,
                          static_folder="../static", template_folder="../templates/app", 
                          url_prefix="/letsgo")

@app_blueprint.route("/", methods=['GET', 'POST'])
@cache.cached(timeout=1)
def index():
    users = User.query.all()
    feedback = Feedback.query.all()
    feedback = random.sample(feedback, min(3, len(feedback)))
    
    form = search()
    if request.method == 'POST' and form.validate_on_submit():
        query = form.search.data
        if query:
            session['destination'] = query
            search_query = SearcHDestination(dest=form.search.data)
            db.session.add(search_query)
            db.session.commit()
            return redirect(url_for('app.searchdestination', destination=session.get("destination")))
        flash("Kindly tell us your search destination.")
    return render_template('index.html', users=users,
                            feedback=feedback, form=form, 
                            dest=session.get("destination"), zip=zip)

@app_blueprint.route("/destinations/<destination>")
def searchdestination(destination):
    dest = session.get("destination")
    return render_template("destinations.html", dest=session.get('destination'))

@app_blueprint.route('/form', methods=['GET', 'POST'])
@cache.cached(timeout=2)
def form():    
    form = FeaturesForm(request.form)
    if request.method == 'POST' and form.validate():
        country = form.country.data
        bururi = Countries.query.filter_by(Country=country).first() #Features.bururi.Region
        region = bururi.Region
        sub_region = bururi.Sub_Region
        age = form.age.data
        companion = form.companion.data
        purpose = form.purpose.data
        activity = form.activity.data
        info = form.info.data
        arrangement = form.arrangement.data
        pack_tra_int = form.pack_tra_int.data
        pack_acc = form.pack_acc.data
        main_nights = int(form.main_nights.data)
        zanzi_nights = int(form.zanzi_nights.data)
        duration = main_nights + zanzi_nights
        stay = staycation(duration)
        try:
            submitted = [country, age, companion, purpose, activity, info, arrangement, pack_tra_int,
                     pack_acc, region, sub_region, duration, stay]
            category, probability = predict_category(submitted)
            regress = [country, age, companion, purpose, activity, info, arrangement, pack_tra_int,
                     pack_acc, main_nights, region, sub_region, duration]
            cost = predict_cost(regress)
            if current_user.is_authenticated:
                user_id = current_user.id
            else:
                user_id = None
            features = Features(country=country, region=region, sub_region=sub_region, age_group=age, travel_with=companion, 
                     purpose=purpose, main_activity=activity, info_source=info, tour_arrangement=arrangement, 
                     package_transport_int=pack_tra_int, package_accomodation=pack_acc,
                     night_mainland=main_nights, night_zanzibar=zanzi_nights, duration=duration,
                     staycation=stay, predicted_category=category, probability=probability, total_cost=cost,
                     user_id=user_id)
            db.session.add(features)
            db.session.flush()
            session['feature_id'] = features.id
            session['user'] = features.user_id
            db.session.commit()
            return redirect(url_for('.predict'))
        except exc.IntegrityError as e:
            db.session.rollback() 
            flash("An error occured while generating your predictions", 'warning')
            raise e
    return render_template('app/form.html', form=form)

@app_blueprint.route('/prediction', methods=['POST', 'GET'])
def predict():
    feature_id = session.get('feature_id')
    feature = Features.query.filter_by(id=feature_id).first_or_404()
    if not feature_id or current_user.is_authenticated and ( current_user.id != session.get('user')):
        flash("Kindly provide your travel details first", category="info")
        return redirect(url_for('.form'))
    form = feedback()
    if request.method == 'POST' and form.validate_on_submit():
        feed = form.feed.data
        sentiment, proba = predict_feed_sentiment(feed)
        user_id = current_user.id
        try:
            user_feedback = Feedback(feed=feed, sentiment=sentiment, probability=proba, 
                                 feature_id=feature_id,user_id= user_id)
            db.session.add(user_feedback)
            db.session.commit()
            flash("Thank you for your feedback.", category="info")
            return redirect(url_for('.predict'))
        except exc.IntegrityError as e:
            flash("Your feedback was not sent, our apologies.", category="info")
            logging.error("Error while adding user feedback: {}".format(e))
    return render_template('app/result.html', feature=feature, form=form)

@app_blueprint.route('/thanks', methods=['GET', 'POST'])
@login_required
def thanks():
    if request.method == 'POST':
        feed = request.form['feedback_button']
        if feed == 'Disatisfied':
                return redirect(url_for('app.sema'))
        flash("Thank you, we're very happy to hear that. 🤗🎆🎇", category='info')
    return render_template('app/thanks.html')

@app_blueprint.route('/feedback', methods=['GET', 'POST'])
@login_required
def sema():
    form = feedbackform(request.form)
    if request.method == 'POST':
        feed = form.feed.data
        senti, proba = predict_feed_sentiment(feed)
        details = Features.query.order_by(Features.id.desc()).first()
        id = details.id
        uhoro = Feedback(feed=feed, sentiment=senti, probability=proba, feature_id=id, user_id=current_user.id)

        db.session.add(uhoro)
        db.session.commit() 

        flash('Feedback received, thank you for your time.')
        return redirect(url_for('suser.activity', username=current_user.username))
 
    return render_template('app/feedback.html', form=form)

flaskapp/webapp/reports/__init__.py
def create_module(app, **kwargs):
    from .routes import reports_blueprint
    
    app.register_blueprint(reports_blueprint)

flaskapp/webapp/reports/routes.py
from flask import Blueprint, flash, url_for, render_template, redirect
from flask_login import login_required 

import pandas as pd

from ..auth import admin_required, has_role, permission_required
from ..mainapp.models import Features
from .report import create_report
from .suites import create_tests

reports_blueprint = Blueprint("report", __name__, 
                              url_prefix="/letsgo/admin/reports")

def get_features():
    data = Features.query.all()
    data_dict = {column.name: [getattr(row, column.name) for row in data] for column in Features.__table__.columns}
    data_df = pd.DataFrame(data_dict)
    
    return data_df

@reports_blueprint.route("/")
@login_required
@admin_required
def show_report():
    current = get_features()
    current.rename(columns={
                            "sub_region": "sub-region"}, inplace=True)
    current['travel_with'].rename({"Alone": "Alone"}, inplace=True)
    current['cost_category'] = current['predicted_category']
    current = current.drop(columns=['user_id', 'total_cost', 'probability'], axis=1)
    
    path = create_report(current=current)
    
    return render_template("/reports/report.html", visuals=path)

@reports_blueprint.route("/tests")
@login_required
@admin_required
def show_tests():
    current = get_features()
    current.rename(columns={"predicted_category": "target",
                            "sub_region": "sub-region"}, inplace=True)
    current = current.drop(columns=['user_id', 'total_cost', 'date', 'id', 'probability'], axis=1)
    
    path = create_tests(i=10, current=current)
    
    return render_template("/reports/tests.html", suites=path)

flaskapp/webapp/users/__init__.py
def create_module(app, **kwargs):
    from .routes import user_blueprint
    app.register_blueprint(user_blueprint, name='suser')

flaskapp/webapp/templates/app/destinations.html
{% extends 'base.html' %}

{% block title %}LetsGO | Destinations {% endblock %}

{% block content %}

{{ dest }}

{% endblock %}

flaskapp/webapp/templates/app/feedback.html
{% extends 'base.html' %}

{% block title %}LetsGo | User Feedback{% endblock %}

{% block content %}
{% include 'include/navigation.html' %}
<section class="feed">
    <div class="moana-form">
        <div class="moana">
            <h1>User Feedback.</h1>
            <p><span>{{ current_user.username | title }}</span>, at LetsGo we really do value 
                feedback from our platform users. Take your time and spill the tea.</p>
        </div>
        <div class="feed-form">
            <form action="{{ url_for('app.sema') }}" method="post">
                {{ form.hidden_tag() }}
                {% for field in form  %}
                    {% if field.widget.input_type != 'hidden' %}
                    <div class="input-box">
                        {{ field.label(class_='label') }}
                        {{ field(class_='text-area') | escape }}
                    </div>
                    <button type="submit" class="send-btn btn-success">Send</button>
                    {% endif %}
                {% endfor %}
            </form>
        </div>                  
    </div>     
</section>
<script type="text/javascript">
    const feedback = document.querySelector("feedback")

    function sendFeedback(){
        alert("Thank for your feedback, admin will be in touch.")
        window.location.href = "{{ url_for('suser.activity', username=current_user.username) }}"
    }
</script>
{% include 'include/footer.html' %}
{% endblock %}

flaskapp/webapp/templates/app/formhelpers.html
{% macro render_field(field) %}
{{ field.csrf_token }}
<dt class="form-label">{{ field.label }}
<dl class="form-input form-control col-sm-5">{{ field(**kwargs)|safe }}
    {% if field.errors %}
    <ul class="errors">
        {% for error in field.errors %}
        <li style="color: red;">{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</dl>
</dt>
{% endmacro %}

flaskapp/webapp/templates/app/result.html
{% extends 'base.html' %}

{% block title %} LetsGo | Prediction Results {% endblock %}

{% block content %}
{% include 'include/navigation.html' %}
<section class="results">
    <div class="result">
        <div class="predictions">
            <h1>What we've got?.</h1>
            <p>Here's your predictions...</p>        
            <div class="another-box">
                <p>
                    From the <span onclick="showDetails()" id="details" title="Click to see"> details</span> 
                    that you have provided, your spending category alongside your predicted total cost will be as follows: 
                </p>
               {% if feature %}
                    <div class="predicted">
                        <h4>Cost Category:<span>{{ feature.predicted_category }}.</span> </h4>
                        <h4>Total Cost: <span>{{ (feature.total_cost / 2300) | round(2) }} USD</span></h4>
                        <h4>Probability:<span>{{ "%.2f" | format(feature.probability) }} %.</span></h4>
                    </div>
                    <div class="details" id="features">      
                        <div class="features">
                            {{ feature.feature }}
                            <p>Country: <strong>{{ feature.country  }}</strong></p>
                            <p>Age group: <strong>{{ feature.age_group }}</strong></p>
                            <p>Travel: <strong>{{ feature.travel_with }}</strong></p>
                            <p>Tour purpose: <strong>{{ feature.purpose }}</strong></p>
                            <p>Main activity: <strong>{{ feature.main_activity }}</strong></p>
                            <p>Info source: <strong>{{ feature.info_source }}</strong></p>
                            <p>Arrangement: <strong>{{ feature.tour_arrangement }}</strong></p>
                            <p>Int'l transport: <strong>{{ feature.package_transport_int }}</strong></p>
                            <p>Accomodation: <strong>{{ feature.package_accomodation }}</strong></p>
                            <p>Nights mainland: <strong>{{ feature.night_mainland }}</strong></p>
                            <p>Nights Zanzibar: <strong>{{ feature.night_zanzibar }}</strong></p>                    
                        </div>
                    </div>
                {% endif %}
                <div class="mawoni">
                    <p>A quick one, how do you feel about the predictions?.</p>
                    <div class="ions">
                        <i class="fa fa-thumbs-up" title="Satisfied" 
                        onclick="showMessage('We are happy you liked the prediction!.')"></i>
                        <!-- <ion-icon name="thumbs-up-outline" title="Satisfied" 
                        onclick="showMessage('We are happy you liked the prediction!.')"></ion-icon>  -->
                        <i class="fa fa-smile" title="Neutral" 
                        onclick="showMessage('We will take that!, fairs. :)')"></i>
                        <!-- <ion-icon name="happy-outline" title="Neutral" 
                        onclick="showMessage('We will take that, tuko happy sana.')"></ion-icon> -->
                        {% if current_user.is_authenticated %}
                            <i class="fa fa-thumbs-down"  title="Disatisfied." onclick="unhappyFeed()" id="Disatisfied"></i>
                            <!-- <ion-icon name="thumbs-down-outline" title="Disatisfied." onclick="unhappyFeed()" id="Disatisfied"></ion-icon>  -->                            
                            <form action="{{ url_for('.predict') }}" method="post" id="mawoni">
                                {{ form.hidden_tag() }}
                                {% for field in form %}
                                    <div class="user-mawoni">
                                        {% if field.type == 'TextAreaField' %}
                                            {{ field(class_='input', placeholder=field.label.text) }}
                                        {% else %}
                                            {{ field(class_='send-btn') }}
                                        {% endif %}                                    
                                    </div>
                                {% endfor %}
                            </form>  
                        {% else %}
                            <i class="fa fa-thumbs-down"  title="Disatisfied." 
                            onclick="showMessage('Trust us, we are equally concerned. Would you kindly provide more information?.')" id="Disatisfied"></i>
                            <!-- <ion-icon name="thumbs-down-outline" title="Disatisfied." onclick="unhappyFeed()" id="Disatisfied"></ion-icon>  -->                            
                            <div id="mawoni">
                                <a href="{{ url_for('auth.signin') }}" style="text-decoration: none;">
                                    <i class="fa fa-info-circle" style="color: brown; font-size: .8em !important;"></i>
                                    <small>Sign to send feedback</small>
                                </a>
                            </div>
                        {% endif %}
                        <div id="feed-modal">
                            <div class="feed-content">
                                <span class="close">&times;</span>
                                <p id="modalText">

                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="recommended">
            <div class="hea-re">
                {% if current_user.is_authenticated %}
                    <h2><span>{{ current_user.username | title }}</span>, Here's places within your budget.</h2>
                {% else %}
                    <h2>All within your budget. It's all yours.</h2>
                {% endif %}                
            </div>
            <div class="places">
                <ul class="gallery">                
                    <li>
                        <figure>
                            <a href=""><img src="/static/images/maasai.jpeg" alt="" srcset=""></a>
                            <figcaption>
                                <main>
                                    <p class="">
                                        <span><i class="fa fa-map-marker"></i>Mara</span>
                                        <span><i class="fa fa-sun"></i>4 Days</span>
                                        <span><i class="fa fa-moon"></i>3 Nights</span>
                                    </p>
                                    <h3>Maasai Mara</h3>
                                    <p>
                                        Experience an authentic encounter with the Maasai community, 
                                        renowned for their cultural richness and unique way of life  
                                    </p>
                                </main>
                                <footer>
                                    <div>
                                        <p class="small">From</p>
                                        <p class="price">$300</p>
                                        <i class="fa fa-arrow-right"></i>
                                    </div>
                                </footer>
                            </figcaption>
                            <i class="fa fa-location"></i>
                        </figure> 
                    </li> 
                    <li>
                        <figure>
                            <a href=""><img src="/static/images/ele.jpg" alt=""></a>
                            <figcaption>
                                <main>
                                    <p>                        
                                        <span><i class="fa fa-map-marker"></i>Serengeti</span>
                                        <span><i class="fa fa-sun"></i>4 Days</span>
                                        <span><i class="fa fa-moon"></i>3 Nights</span>
                                    </p>
                                    <h3>Serengeti</h3>
                                    <p>Book your safari today and get ready to be awed by the beauty of the African savannah!</p>
                                </main>
                                <footer>
                                    <div>
                                        <p class="small">From</p>
                                        <p class="price">$100</p>
                                        <i class="fa fa-arrow-right"></i>
                                    </div>
                                </footer>
                            </figcaption>
                            <i class="fa fa-location"></i>
                        </figure>
                    </li> 
                </ul>
            </div>
            <div class="btn-activity">
                {% if current_user.is_authenticated %}
                    <button type="button" class="activity-btn" onclick="toActivity()">Discover More.</button>
                {% else %}
                    <button type="button" class="activity-btn" onclick="toActivity()">Sign In to Discover More.</button>
                {% endif  %}                
            </div>            
        </div>        
    </div>
</section>
<section class="teaser">
    <div class="another">
        <div class="row">
            <h3> Feels like a rollercoaster?.</h3>
            <p>Give it another try?.</p>
            <div class="btns">
                <button type="button" onclick="toForm()" class="result-btn">Of Course.</button>
                <button type="button" onclick="toThanks()" class="result-btn">I'm good.</button>                
            </div>
        </div>
    </div>
</section>
{% include 'include/footer.html' %}
{% endblock %}
{% block js %}
    {{ super() }}
    <script type="text/javascript">
        var modal  = document.querySelector("#feed-modal");
        var exi = document.querySelector(".close");
        var is = document.querySelectorAll("i");

        is.forEach(function(i){
            i.addEventListener('click', ()=>{
                is.forEach(function(otherIs){
                    otherIs.style.pointerEvents = 'none';
                    otherIs.classList.remove('active');
                });

                i.classList.toggle('active');
            });
        });

        function showMessage(message){
            document.getElementById("modalText").innerHTML = message;
            modal.classList.add("active");
        }
    
        exi.onclick = function(){
            modal.style.display = "none";
        }
      
        window.onclick = function(event){
            if (event.target == modal){
            modal.style.display = "none";
            }
        }
        function toActivity(){
            window.location.href = "{{ url_for('suser.activity', username=current_user.username) }}"
        }
        function toSign(){
            window.location.href = "{{ url_for('auth.signin') }}"
        }
        function toForm(){
            window.location.href = "{{ url_for('app.form') }}"
        }
        function toThanks(){
            window.location.href = "{{ url_for('app.thanks') }}"
        }
    
        var showDetails = document.getElementById("features")
        showDetails.addEventListener('click', function(){
            showDetails.classList.add('features-show')
        })
    </script>
{% endblock %}