flaskapp/webapp/admin/__init__.py
from flask_admin import Admin
from flask_admin.consts import ICON_TYPE_FONT_AWESOME
from webapp import db
# from .routes import CustomView, CustomModelView, CustomFileAdmin
from ..auth.models import User, Role
from ..mainapp.models import Features, Feedback,  Countries, SearcHDestination
from ..users.models import Search

import csv 
admin = Admin()


def create_module(app, **kwargs):
    #admin.init_app(app)
    #admin.add_view(CustomView(name='Custom'))
    #user_model = User
    #models = [user_model, Role, Features, Feedback, SearcHDestination, Search, Countries]
    #for model in models:
    #    admin.add_view(CustomModelView(model, db.session, category='Database Models'))

    #admin.add_view(CustomFileAdmin(app.static_folder,'/static/', name='Static Files'))

    from .routes import admin_blueprint
    app.register_blueprint(admin_blueprint)


flaskapp/webapp/admin/routes.py
import os 
import pickle
import random
import datetime
from datetime import datetime, timedelta
import base64
import io

from flask import (Blueprint,render_template, redirect, url_for, 
                   flash, session, request, jsonify, current_app, abort)
from flask_login import login_required, current_user
from sqlalchemy import exc

import pandas as pd
import matplotlib.pyplot as plt

from webapp import db
from ..auth import has_role, permission_required, admin_required
from ..auth.models import User, Role
from ..mainapp.models import Features, Feedback
from .models import Admin
from .forms import editAdmin, editProfile
from ..reports.utils import get_model_score 


admin_blueprint = Blueprint('admin', __name__,
                            static_folder='../static/admin',
                            template_folder='../templates/admin',
                            url_prefix="/letsgo/admin"
                            )

dire = os.path.dirname(__file__)
model = pickle.load(open(os.path.join(dire, "pickle_objects", "Cat_v3.pkl"), 'rb'))
senti_clf = pickle.load(open(os.path.join(dire, "pickle_objects", "classifier.pkl"), 'rb'))
importance = pd.read_csv("/home/riri/Desktop/expenditure/src/models/notebooks/classification/Importances.csv")
imps = importance.to_dict(orient='records')
importance.plot(kind='barh')
plt.xlabel('Importance')
plt.ylabel('Features')
plt.title('Feature Importance')

img = io.BytesIO()
plt.savefig(img, format='png')
img.seek(0)

plot_url = base64.b64encode(img.getvalue()).decode()

def fetch_data():
    results = Features.query.all()
    return [{column.name: getattr(row, column.name) for column in row.__table__.columns} for row in results]

@admin_blueprint.route("/features", methods=['GET', 'POST'])
@login_required
@admin_required
def fetch_features():
    result = fetch_data()
    return jsonify(result)

@admin_blueprint.route("/")
@login_required
@admin_required
def admindashboard():
    date_from = datetime.now() - timedelta(days=90)
    all_u = User.query.all()
    new = User.query.filter(User.date_created > date_from).all()
    users = random.sample(all_u, min(3, len(all_u)))
    feedback = Feedback.query.all()
    feedback = random.sample(feedback, min(5, len(feedback))) 
    features = Features.query.order_by(Features.date.desc()).all()
    feats = random.sample(features, min(5, len(features)))
    late_feed = Feedback.query.order_by(Feedback.date.desc()).limit(10).all()
    return render_template('dashboard.html', users=users, all=all_u, 
                           score=get_model_score(), new=new, model=model, 
                           feedback=feedback, features=feats, all_f=features,
                           feed=late_feed, imps=imps, plot=plot_url)
    
@admin_blueprint.route("/users", methods=['GET', 'POST'])
@login_required
@admin_required
def users():
    features = Features.query.all()
    page = request.args.get('page', 1, type=int)
    users = User.query.order_by(User.last_seen.desc())
    pagination = db.paginate(users, page=page, per_page=7, error_out=False)
    users = pagination.items
    return render_template("admin/users.html", users=users, 
                           pagination=pagination, features=features)

@admin_blueprint.route("/feedback")
@login_required
@admin_required
def feed():
    users = User.query.all()
    feat = Features.query.all()
    page = request.args.get('page', 1, type=int)
    feed = Feedback.query.order_by(Feedback.date.desc())
    pagination = db.paginate(feed, page=page, per_page=10, error_out=False)
    feedback = pagination.items
    return render_template("admin/feedback.html", feedback=feedback, pagination=pagination, 
                           features=feat, users=users, zip=zip, enumerate=enumerate)
@admin_blueprint.route("/all_features")
@login_required
@admin_required
def features():
    users = User.query.all()
    feats = Features.query.order_by(Features.date.asc()).order_by(Features.id.asc())
    page = request.args.get('page', 1, type=int)
    pagination = db.paginate(feats, page=page, per_page=10, error_out=False)
    feats = pagination.items

    return render_template("admin/features.html", features=feats, 
                           pagination=pagination, users=users)

@admin_blueprint.route("/<string:username>/admin-profile/")
@login_required
@admin_required
def profile(username):
    user = Admin.query.filter_by(username=username).first() or User.query.filter_by(username=username).first()
    if not user:
        flash("User not found or user is not an administrator", category="warning") 
    return render_template("admin/profile.html", user=user)


@admin_blueprint.route("/<string:username>/admin-profile/update", methods=['POST', 'GET'])
@login_required
@admin_required
def edit_admin(username):
    user = Admin.query.filter_by(username=username).first_or_404() 
    if not user:
        user = User.query.filter_by(username=username).first()
    if not user.is_administrator():
        return redirect(url_for('.user_profile', username=user.username))
    form = editAdmin()
    if form.validate_on_submit():
        admin = Admin()

        admin.name = form.name.data
        admin.email = form.email.data
        admin.username = user.username
        admin.mobile = form.mobile.data
        admin.agency = form.agency.data
        admin.agency_email = form.agency_email.data
        admin.agency_mobile = form.agency_mobile.data
        admin.agency_address = form.agency_address.data
        try:
            db.session.add(admin)
            db.session.commit()
            flash("Administrator profile details updated succesfully", category="info")
            return redirect(url_for('.user_profile', username=user.username))
        except BaseException as e:
            db.session.rollback()
            flash("Administrator profile not updated!: {}".format(e), category="warning")
            return redirect(url_for('.profile', username=current_user.username))
    
    form.name.data = user.name
    form.email.data = user.email
    form.agency.data = user.agency
    form.mobile.data = user.mobile
    form.agency_email.data = user.agency_email
    form.agency_address.data = user.agency_address
    form.agency_mobile.data = user.agency_mobile
    
    return render_template("admin/editadmin.html", form=form, user=user)

@admin_blueprint.route('/<string:username>@user-profile', methods=['GET', 'POST'])
@login_required
@admin_required
def user_profile(username):
    user = User.query.filter_by(username=username).first()
    if not user:
        flash('No such user with the given username', 'warning')
        return redirect(url_for('.users')) 
    
    return render_template('/user/view.html', user=user)

@admin_blueprint.route('/@<string:username>/user-profile/update', methods=['GET', 'POST'])
@login_required
@admin_required
def update_profile(username):
    user = Admin.query.filter_by(username=username).first() or User.query.filter_by(username=username).first()
    if not user:
        flash("User with that such username doesn't exist!.", "warning")
        return redirect(url_for('.users'))
    form = editProfile(user=user)
    if request.method == 'POST' and form.validate_on_submit():
        user.email = form.email.data
        user.full_name = form.name.data
        user.username = form.username.data
        user.mobile = form.mobile.data
        user.role = Role.query.get(form.role.data)
        user.location = form.location.data
        user.about = form.about.data
        user.confirmed = form.confirmed.data
        try:
            db.session.add(user)
            db.session.commit()
            flash('User details updated successfully.', category="info")
            return redirect(url_for('.user_profile', username=user.username))
        except Exception:
            db.session.rollback()
            flash("User details not updated.", 'info')
    
    form.email.data = user.email
    form.name.data = user.full_name
    form.username.data = user.username
    form.role.data = user.role
    form.location.data = user.location
    form.about.data = user.about
    form.confirmed.data = user.confirmed
    
    return render_template('/user/editProfile.html', form=form, user=user)

@admin_blueprint.route('/remover_user/<username>/', methods=['GET', 'POST'])
@login_required
@admin_required
def delete_profile(username):
    user = User.query.filter_by(username=username).first()
    if user:
        try: 
            db.session.delete(user)
            db.session.commit()
            flash(f"User {user.username} removed successfully", category="info")
            return redirect(url_for('.users'))
        except Exception:
            db.session.rollback()
            flash("User couldn't be removed.", 'info')
            return redirect(url_for('.users'))
    else:
        flash("User with such username not found", category='warning')
        return redirect(url_for('.users'))

flaskapp/webapp/api_1_0/__init__.py
from flask_restful import Api
from .feedback.controllers import FeedbackApi

rest = Api()

def create_module(app, **kwargs):
       rest.add_resource(
            FeedbackApi,
            '/api/feed',
            '/api/feed/<int:feed_id>')
       rest.init_app(app)

flaskapp/webapp/babel/routes.py
from flask import Blueprint, redirect, url_for, session

babel_blueprint = Blueprint('babel', __name__, url_prefix="/letsgo")

@babel_blueprint.route('/<string:locale>')
def index(locale):
    session[locale] = locale
    return redirect(url_for('app.index'))

flaskapp/webapp/mainapp/routes.py
import logging

import json
import random

import numpy as np

from sqlalchemy import exc

from flask import render_template, url_for, redirect, Blueprint, flash, request, session, jsonify
from flask_login import login_required, current_user

from webapp import db, cache
from webapp.auth.models import User
from .models import Countries, Features, Feedback, SearcHDestination
from .forms import FeaturesForm, feedbackform, search

from ..users.forms import feedback
from ..predict import predict_category, predict_cost, predict_feed_sentiment, staycation
from ..train import train_clf


app_blueprint = Blueprint('app', __name__,
                          static_folder="../static", template_folder="../templates/app", 
                          url_prefix="/letsgo")

@app_blueprint.route("/", methods=['GET', 'POST'])
@cache.cached(timeout=1)
def index():
    users = User.query.all()
    feedback = Feedback.query.all()
    feedback = random.sample(feedback, min(3, len(feedback)))
    
    form = search()
    if request.method == 'POST' and form.validate_on_submit():
        query = form.search.data
        if query:
            session['destination'] = query
            search_query = SearcHDestination(dest=form.search.data)
            db.session.add(search_query)
            db.session.commit()
            return redirect(url_for('app.searchdestination', destination=session.get("destination")))
        flash("Kindly tell us your search destination.")
    return render_template('index.html', users=users,
                            feedback=feedback, form=form, 
                            dest=session.get("destination"), zip=zip)

@app_blueprint.route("/destinations/<destination>")
def searchdestination(destination):
    dest = session.get("destination")
    return render_template("destinations.html", dest=session.get('destination'))

@app_blueprint.route('/form', methods=['GET', 'POST'])
@cache.cached(timeout=2)
def form():    
    form = FeaturesForm(request.form)
    if request.method == 'POST' and form.validate():
        country = form.country.data
        bururi = Countries.query.filter_by(Country=country).first() #Features.bururi.Region
        region = bururi.Region
        sub_region = bururi.Sub_Region
        age = form.age.data
        companion = form.companion.data
        purpose = form.purpose.data
        activity = form.activity.data
        info = form.info.data
        arrangement = form.arrangement.data
        pack_tra_int = form.pack_tra_int.data
        pack_acc = form.pack_acc.data
        main_nights = int(form.main_nights.data)
        zanzi_nights = int(form.zanzi_nights.data)
        duration = main_nights + zanzi_nights
        stay = staycation(duration)
        try:
            submitted = [country, age, companion, purpose, activity, info, arrangement, pack_tra_int,
                     pack_acc, region, sub_region, duration, stay]
            category, probability = predict_category(submitted)
            regress = [country, age, companion, purpose, activity, info, arrangement, pack_tra_int,
                     pack_acc, main_nights, region, sub_region, duration]
            cost = predict_cost(regress)
            if current_user.is_authenticated:
                user_id = current_user.id
            else:
                user_id = None
            features = Features(country=country, region=region, sub_region=sub_region, age_group=age, travel_with=companion, 
                     purpose=purpose, main_activity=activity, info_source=info, tour_arrangement=arrangement, 
                     package_transport_int=pack_tra_int, package_accomodation=pack_acc,
                     night_mainland=main_nights, night_zanzibar=zanzi_nights, duration=duration,
                     staycation=stay, predicted_category=category, probability=probability, total_cost=cost,
                     user_id=user_id)
            db.session.add(features)
            db.session.flush()
            session['feature_id'] = features.id
            session['user'] = features.user_id
            db.session.commit()
            return redirect(url_for('.predict'))
        except exc.IntegrityError as e:
            db.session.rollback() 
            flash("An error occured while generating your predictions", 'warning')
            raise e
    return render_template('app/form.html', form=form)

@app_blueprint.route('/prediction', methods=['POST', 'GET'])
def predict():
    feature_id = session.get('feature_id')
    feature = Features.query.filter_by(id=feature_id).first_or_404()
    if not feature_id or current_user.is_authenticated and ( current_user.id != session.get('user')):
        flash("Kindly provide your travel details first", category="info")
        return redirect(url_for('.form'))
    form = feedback()
    if request.method == 'POST' and form.validate_on_submit():
        feed = form.feed.data
        sentiment, proba = predict_feed_sentiment(feed)
        user_id = current_user.id
        try:
            user_feedback = Feedback(feed=feed, sentiment=sentiment, probability=proba, 
                                 feature_id=feature_id,user_id= user_id)
            db.session.add(user_feedback)
            db.session.commit()
            flash("Thank you for your feedback.", category="info")
            return redirect(url_for('.predict'))
        except exc.IntegrityError as e:
            flash("Your feedback was not sent, our apologies.", category="info")
            logging.error("Error while adding user feedback: {}".format(e))
    return render_template('app/result.html', feature=feature, form=form)

@app_blueprint.route('/thanks', methods=['GET', 'POST'])
@login_required
def thanks():
    if request.method == 'POST':
        feed = request.form['feedback_button']
        if feed == 'Disatisfied':
                return redirect(url_for('app.sema'))
        flash("Thank you, we're very happy to hear that. 🤗🎆🎇", category='info')
    return render_template('app/thanks.html')

@app_blueprint.route('/feedback', methods=['GET', 'POST'])
@login_required
def sema():
    form = feedbackform(request.form)
    if request.method == 'POST':
        feed = form.feed.data
        senti, proba = predict_feed_sentiment(feed)
        details = Features.query.order_by(Features.id.desc()).first()
        id = details.id
        uhoro = Feedback(feed=feed, sentiment=senti, probability=proba, feature_id=id, user_id=current_user.id)

        db.session.add(uhoro)
        db.session.commit() 

        flash('Feedback received, thank you for your time.')
        return redirect(url_for('suser.activity', username=current_user.username))
 
    return render_template('app/feedback.html', form=form)

flaskapp/webapp/reports/__init__.py
def create_module(app, **kwargs):
    from .routes import reports_blueprint
    
    app.register_blueprint(reports_blueprint)

flaskapp/webapp/users/__init__.py
def create_module(app, **kwargs):
    from .routes import user_blueprint
    app.register_blueprint(user_blueprint, name='suser')

flaskapp/webapp/templates/include/footer.html
<section class="footer">
    <div class="container footer-wrapper">
        <div class="row">
            <div class="newsletter">
                <div class="row">
                    <div class="col-md-3">
                        <div class="footer-logo">
                            <h4><i class="fa fa-paper-plane fa-3x" style="font-size: 50px;"></i><span>LetsGO</span></h4>
                            <p>Where future meets travel.</p>                        
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="emailing">
                            <div class="loop">
                                <h1>Stay on the Loop.</h1>
                                <p>Subscribe to our mailing list to be the first one to receive personalised and hot travel deals tailored just for you.</p>                            
                            </div>
                            <div class="input-group">
                                <input class="form-control" type="email" name="email" id="email" placeholder="Enter email">
                                <div class="input-group-append">
                                    <button type="submit" class="input-group-text">Subscribe</button>
                                </div>                            
                            </div>
                        </div>
                    </div>                    
                </div>
            </div>
        </div>
        <div class="row">
            <div class="footer-aob">
                <div class="row">
                    <div class="col-md-3">
                        <ul class="featured-terms">
                            <h3>Featured.</h3>
                            <li><a href="">Deals & Offers</a></li>
                            <li><a href="">Data Collection Policy</a></li>
                            <li><a href="">Model Biasness</a></li>
                            <li><a href="">Terms and Conditions</a></li>
                            <li><a href="">About</a></li>
                        </ul>                     
                    </div> 
                    <div class="col-md-4">
                        <ul class="contacts">
                            <h3>Quick Contacts.</h3>
                            <li>
                                <i class="fa fa-phone"></i>
                                <a href="tel: +254758630202" title="Give us a call.">+254 758-630-202</a>
                            </li>
                            <li>
                                <i class="fa fa-envelope"></i>
                                <a href="mailto:info@letsgo@gmail.com" target="_top" title="Send us an email today.">info.letsgo@gmail.com</a>
                            </li>
                            <li>
                                <i class="fa fa-map-marker"></i>
                                <a href="http://maps.google.com/?q=Kasarani Maternity, Nairobi." title="Our Offices.">Gigiri, Muthangari, Nairobi KE.</a>
                            </li>
                        </ul>
                    </div> 
                    <div class="col-md-5">
                        <li class="social-icons">
                            <h3>Developer Contacts.</h3>
                            <ul>
                                <a href="mailto:jamesriri03@gmail.com"><i class="fa fa-envelope"></i></a>
                            </ul>
                            <ul>
                                <a href="https://github.com/Njaramba-Riri/"><i class="fab fa-github"></i></a>
                            </ul>
                            <ul>
                                <a href="https://www.linkedin.com/in/riri-njaramba/"><i class="fab fa-linkedin"></i></a>
                            </ul>
                            <ul>
                                <a href="https://twitter.com/icy_riri"><i class="fab fa-twitter"></i></a>
                            </ul>
                            <ul>
                                <a href="https://medium.com/@jamesriri03"><i class="fab fa-medium"></i></a>
                            </ul>
                        </li>
                    </div>
                </div>
            </div>
            <hr>
            <div class="endnote">
                <p class="proud">Made With <i class="fa fa-fire"></i> and<i class="fa fa-heart"></i>by LetsGo Team.</p>
                <p class="copyright">
                    &copy;
                    <span class="current-year">2024</span>.
                    <span>
                        <i class='fas fa-paper-plane'></i>LetsGo
                    </span>.
                    <span>All rights reserved</span>
                </p>                
            </div>
        </div>
    </div>
</section>

flaskapp/webapp/templates/include/loader.html
<div class="loader-content">
    <div class="loader">
        <svg viewBox="0 0 400 160">
            <text x="50%" y="50%" dy=".32em" text-anchor="middle" class="loader-body">
            LetsGo
            </text>
            <text x="50%" y="50%" dy=".32em" dx="1.6em" text-anchor="middle" class="loader-body">         
            </text>
        </svg>        
    </div>
</div>

flaskapp/webapp/templates/include/nav.html
<section class="navigation">
    <nav class="navbar navbar-expand nav-inverse" id="Nav" role="navigation">
        <div class="container-fluid">
            <div class="navbar-brand">
                <i class="fa fa-paper-plane fa-3x" style="color: rgb(255, 255, 255);"></i>
                <span class="brand-name">LetsGO</span></span>
            </div>
            <ul class="navbar-nav mr-auto">
                {% if current_user.confirmed and current_user.is_administrator() %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('admin.admindashboard')}}">
                        Admin Dashboard<span class="sr-only">(current)</span></a>
                </li>            
                {% elif current_user.is_authenticated and not current_user.is_administrator() %}
                <div class="nav-item ">
                    <a class="nav-link" href="{{ url_for('app.index') }}">
                        Home
                    </a>
                </div>
                <li class="nav-item">
                    <a href="{{ url_for('app.form') }}" class="nav-link">Predict</a>
                </li>
                <div class="nav-item">
                    <a href="#" class="nav-link">About</a>
                </div>
                <li class="nav-item">
                    <a href="" class="nav-link">Top Destinations</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="dropdown-toggle dropdown-link-title text-uppercase nav-link" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ current_user.username }}
                    </a>
                    <ul class="dropdown-menu show-dropdown" aria-labelledby="dropdowwnMenuLink" id="dropdownMenu">
                        <li>
                            <a class="dropdown-item" href="{{ url_for('suser.profile', username=current_user.username) }}">
                                My Profile<i class="fa fa-fw fa-user-circle" style="margin-left: 5px;"></i>
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{{ url_for('suser.update', username=current_user.username) }}">
                                Edit Profile <i class="fa fa-user"></i>
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{{ url_for('auth.changePassword', username=current_user.username) }}">
                                Change Password<i class="fa fa-lock" style="margin-left: 10px;"></i>
                            </a>
                        </li>
                        <hr>
                        <li>
                            <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                                Logout<i class="fa fa-fw fa-sign-out" style="margin-left: 5px;"></i>
                            </a>
                        </li>
                    </ul>
                </li>
                {% elif current_user.is_anonymous %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('app.index') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link login-btn dropdown-btn" href="{{ url_for('auth.signin') }}">Login</a>
                </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="dropdown-toggle" id="langDropdown" data-bs-toggle="dropdown">
                        Language
                    </a>
                    <div class="dropdown-menu" aria-labelledby="langDropdown">
                        <a class="dropdown-item" href="{{ url_for('babel.index', locale='en') }}">English</a>
                        <a class="dropdown-item" href="{{ url_for('babel.index', locale='sw') }}">Swahili</a>
                        <a class="dropdown-item" href="{{ url_for('babel.index', locale='es') }}">Spanish</a>
                        <a class="dropdown-item" href="{{ url_for('babel.index', locale='de') }}">German</a>
                        <a class="dropdown-item" href="{{ url_for('babel.index', locale='fr') }}">French</a>
                        <a class="dropdown-item" href="{{ url_for('babel.index', locale='pt') }}">Portuguese</a>
                    </div>
                </li>
            </ul>
            </div>
        </div>
    </nav>  
</section>

flaskapp/webapp/templates/include/navigation.html
<div class="navigation" id="navigation">
    <div class="bar">
        <ul>
            <div class="item">
                <li>
                    <i class="fa fa-paper-plane"></i>
                    <a href="{{ url_for('app.index') }}">LetsGo</a>
                </li>
            </div>
            {% if not current_user.is_authenticated %}
            <div class="item">
                <li>
                    <a href="{{ url_for('app.index') }}#about">About</a>
                </li>
            </div>  
            <div class="item">
                <li>
                    <a href="{{ url_for('app.index') }}#destinations">Top Destinations</a>
                </li>
            </div>
            {% endif %}  
            {% if current_user.is_authenticated and current_user.is_administrator() %}
            <div class="item">
                <li>
                    <a href="{{url_for('admin.admindashboard')}}">Dashboard</a>
                </li>
            </div>
            <div class="item">
                <li>
                    <a href="{{ url_for('admin.profile', username=current_user.username) }}">{{ current_user.username | title}}</a>
                </li>
            </div>
            {% elif current_user.is_authenticated and not current_user.is_administrator() %}
            <div class="item">
                <li>
                    <a href="{{ url_for('app.form') }}">Predict</a>
                </li>
            </div>
            <div class="item">
                <li>
                    <a href="{{ url_for('suser.activity', username=current_user.username) }}#destinations">Destinations</a>
                </li>
            </div>
            <div class="item">
                <div id="dropdown">
                    <span style="color: aliceblue;">{{ current_user.username | upper }}</span>
                </div>                
                <li>
                    <ol class="dropdown">
                        <li>
                            <a href="{{ url_for('suser.profile', username=current_user.username) }}">My Profile</a>
                            <ion-icon name="person-circle-outline"></ion-icon>
                        </li>
                        <li>
                            <a href="{{ url_for('suser.update', username=current_user.username) }}">Edit Profile</a>
                            <ion-icon name="create-outline"></ion-icon>
                        </li>
                        <li>
                            <a href="{{ url_for('auth.changePassword', username=current_user.username) }}">Change Password</a>
                            <ion-icon name="lock-open-outline"></ion-icon>
                        </li>
                        <li id="out">
                            <a href="{{ url_for('auth.logout') }}">Sign Out</a>
                            <ion-icon name="log-out-outline"></ion-icon>
                        </li>
                    </ol>
                </li>
            </div>
            {% elif current_user.is_anonymous %}
            <div class="item">
                <li class="sign">
                    <a href="{{ url_for('auth.signin') }}">Login</a>
                </li>
            </div>
            {% endif %}
        </ul>
    </div>
</div>